export const apiTransform = data => {
  return {
    userConfig: {
      theme: {
        fontSize: data.config.theme.font_size,
        background: data.config.theme.background,
        text: data.config.theme.text,
        linkText: data.config.theme.link_text,
        buttonBackground: data.config.theme.button_background,
        buttonText: data.config.theme.button_text,
      },
      layout: {
        appearance: data.config.layout.appearance,
        position: data.config.layout.position,
      },
      content: {
        cookiePolicyUrl: data.config.content.cookie_policy_url,
        cookiePolicyLinkText: data.config.content.cookie_policy_link_text,
        dialogTitle: data.config.content.dialog_title,
        dialogMessage: data.config.content.dialog_message,
        dialogSavePreferencesButton: data.config.content.dialog_save_preferences_button,
        dialogAcceptAllButton: data.config.content.dialog_accept_all_button,
        dialogRejectAllButton: data.config.content.dialog_reject_all_button,
        widgetBannerMessage: data.config.content.widget_banner_message,
        widgetPillMessage: data.config.content.widget_pill_message,
        widgetManagePreferencesButton: data.config.content.widget_manage_preferences_button,
        widgetRejectAllButton: data.config.content.widget_reject_all_button,
        widgetAcceptAllButton: data.config.content.widget_accept_all_button,
        widgetShowCookiesButton: data.config.content.widget_show_cookies_button,
        widgetHideCookiesButton: data.config.content.widget_hide_cookies_button,
        cookieEssentialTitle: data.config.content.cookie_essential_title,
        cookieEssentialDescription: data.config.content.cookie_essential_description,
        cookieFunctionalTitle: data.config.content.cookie_functional_title,
        cookieFunctionalDescription: data.config.content.cookie_functional_description,
        cookieMarketingTitle: data.config.content.cookie_marketing_title,
        cookieMarketingDescription: data.config.content.cookie_marketing_description,
        cookieAnalyticsTitle: data.config.content.cookie_analytics_title,
        cookieAnalyticsDescription: data.config.content.cookie_analytics_description,
        cookieUnclassifiedTitle: data.config.content.cookie_unclassified_title,
        cookieUnclassifiedDescription: data.config.content.cookie_unclassified_description,
        cookieHeadingPlatform: data.config.content.cookie_heading_platform,
        cookieHeadingNameDescription: data.config.content.cookie_heading_name_description,
        cookieHeadingRetention: data.config.content.cookie_heading_retention,
      },
      functionality: {
        allowPreferences: data.config.functionality.allow_preferences,
        blockInteraction: data.config.functionality.block_interaction,
        blockScripts: data.config.functionality.block_scripts,
        hasRejectAll: data.config.functionality.has_reject_all,
        googleConsentMode: data.config.functionality.google_consent_mode,
      },
    },
    detectedCookies: {
      "Essential Cookies": {
        slug: "essential-cookies",
        label: data.cookies.essential.label,
        description: data.cookies.essential.description,
        total: data.cookies.essential.total,
        keys: data.cookies.essential.keys,
        cookies: data.cookies.essential.cookies,
      },
      Functional: {
        slug: "functional",
        label: data.cookies.functional.label,
        description: data.cookies.functional.description,
        total: data.cookies.functional.total,
        keys: data.cookies.functional.keys,
        cookies: data.cookies.functional.cookies,
      },
      Marketing: {
        slug: "marketing",
        label: data.cookies.marketing.label,
        description: data.cookies.marketing.description,
        total: data.cookies.marketing.total,
        keys: data.cookies.marketing.keys,
        cookies: data.cookies.marketing.cookies,
      },
      Analytics: {
        slug: "analytics",
        label: data.cookies.analytics.label,
        description: data.cookies.analytics.description,
        total: data.cookies.analytics.total,
        keys: data.cookies.analytics.keys,
        cookies: data.cookies.analytics.cookies,
      },
      Unclassified: {
        slug: "unclassified",
        label: data.cookies.unclassified.label,
        description: data.cookies.unclassified.description,
        total: data.cookies.unclassified.total,
        keys: data.cookies.unclassified.keys,
        cookies: data.cookies.unclassified.cookies,
      },
    },
  };
};
